# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0003_auto_20170427_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
