# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0004_auto_20170429_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pTime',
            field=models.DateTimeField(),
        ),
    ]
