# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0005_auto_20170429_1419'),
        ('fume', '0004_reward_expirationdate'),
    ]

    operations = [
    ]
